DROP TABLE IF EXISTS expense CASCADE;
DROP TABLE IF EXISTS expense_category CASCADE;
DROP TABLE IF EXISTS income CASCADE;
DROP TABLE IF EXISTS income_category CASCADE;

CREATE TABLE expense_category
(
    id   bigserial PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE expense
(
    id                  bigserial PRIMARY KEY,
    description         VARCHAR(255),
    amount              DOUBLE PRECISION,
    date                TIMESTAMP,
    expense_category_id bigint,
    FOREIGN KEY (expense_category_id) REFERENCES expense_category (id)
);

CREATE TABLE income_category
(
    id   bigserial PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE income
(
    id                  bigserial PRIMARY KEY,
    description         VARCHAR(255),
    amount              DOUBLE PRECISION,
    date                TIMESTAMP,
    income_category_id bigint,
    FOREIGN KEY (income_category_id) REFERENCES income_category (id)
);

-- drop table if exists expense CASCADE;
-- drop table if exists expense_category CASCADE;
-- drop table if exists income CASCADE;
-- drop table if exists income_category CASCADE;
--
-- CREATE TABLE expense_category
-- (
--     id   bigint generated by default as identity,
--     name VARCHAR(255),
--     PRIMARY KEY (id)
-- );
--
-- CREATE TABLE expense
-- (
--     id                  bigint generated by default as identity,
--     description         VARCHAR(255),
--     amount              DOUBLE PRECISION,
--     date                TIMESTAMP,
--     expense_category_id bigint,
--     PRIMARY KEY (id),
--     FOREIGN KEY (expense_category_id) REFERENCES expense_category (id)
-- );
--
-- CREATE TABLE income_category
-- (
--     id   bigint generated by default as identity,
--     name VARCHAR(255),
--     PRIMARY KEY (id)
-- );
--
-- CREATE TABLE income
-- (
--     id                  bigint generated by default as identity,
--     description         VARCHAR(255),
--     amount              DOUBLE PRECISION,
--     date                TIMESTAMP,
--     income_category_id bigint,
--     PRIMARY KEY (id),
--     FOREIGN KEY (income_category_id) REFERENCES income_category (id)
-- );